/*
 * FileChooserMain.java
 *
 * Created on 2008/11/21, 16:08
 * @author  tadaki
 */
package fileChooser;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class FileChooserMain extends javax.swing.JFrame {

    private File dir;

    /**
     * Creates new form FileChooserMain
     */
    public FileChooserMain() {
        initComponents();
        dir = new File(".");//現在のディレクトリ
//        System.out.println(dir.getAbsoluteFile().getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        quit = new javax.swing.JButton();
        open = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File Chooser Main");

        buttons.setBackground(new java.awt.Color(255, 255, 204));

        quit.setBackground(new java.awt.Color(204, 255, 255));
        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        buttons.add(quit);

        open.setBackground(new java.awt.Color(255, 204, 0));
        open.setText("OPEN");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        buttons.add(open);

        clear.setBackground(new java.awt.Color(255, 204, 204));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        buttons.add(clear);

        save.setBackground(new java.awt.Color(204, 255, 204));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        buttons.add(save);
        buttons.add(fileNameLabel);

        getContentPane().add(buttons, java.awt.BorderLayout.NORTH);

        textArea.setColumns(80);
        textArea.setRows(20);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * openボタンをクリックし、ファイルを読みこみテキストエリアに表示
     *
     * @param evt
     */
private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
    //file chooserを生成し、テキストファイルに限定
    JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(dir);
    chooser.setFileFilter(
            new FileNameExtensionFilter("Text File", "txt"));

    int returnVal = chooser.showOpenDialog(this);//ダイアログの表示
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();//選択したファイル
        textArea.setText(FileUtilGUI.openFile(file));//textAreaへ表示
        textArea.setVisible(true);
        fileNameLabel.setText(file.getName());
        dir = file.getParentFile();
    }
}//GEN-LAST:event_openActionPerformed

    /**
     * テキストエリアのクリア
     *
     * @param evt
     */
private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    textArea.setText(null);
}//GEN-LAST:event_clearActionPerformed

    /**
     * テキストエリア内のテキストをファイルへ保存
     *
     * @param evt
     */
private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    //file chooserを生成し、テキストファイルに限定
    JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(dir);
    chooser.setFileFilter(new FileNameExtensionFilter("Text File", "txt"));

    int returnVal = chooser.showSaveDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        FileUtilGUI.saveFile(file, textArea.getText());
        fileNameLabel.setText(file.getName());
        dir = file.getParentFile();
    }
}//GEN-LAST:event_saveActionPerformed
    /**
     * quitボタンを押すと、終了
     *
     * @param evt
     */
    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new FileChooserMain().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JButton clear;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton open;
    private javax.swing.JButton quit;
    private javax.swing.JButton save;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
