package simpleTimer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tadaki
 */
public class SimpleTimer extends javax.swing.JFrame implements Runnable {

    private final Timer timerLabel;
    private final Dimension timerDimension = new Dimension(400, 50);
    private final SetTimePanel setTimePanel;
    private Thread runner = null;
    private volatile boolean running = false;
    private final Color backgroundNormal;
    private final Color backgroundOver=Color.RED;

    /**
     * Creates new form SimpleTimer
     */
    public SimpleTimer() {
        initComponents();
        timerLabel = new Timer();
        timerLabel.setMaximumSize(timerDimension);
        timerLabel.setPreferredSize(timerDimension);
        timerLabel.setFont(new Font("Dialog", Font.PLAIN, 24));
        timerLabel.setHorizontalAlignment(JLabel.CENTER);

        showPanel.add(timerLabel);
        setTimePanel = new SetTimePanel();
        backgroundNormal = showPanel.getBackground();
        pack();
    }

    @Override
    public void run() {
        while (running) {
            if (!timerLabel.setTime()) {
                showPanel.setBackground(backgroundOver);
            }
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        quit = new javax.swing.JButton();
        toggle = new javax.swing.JToggleButton();
        setTime = new javax.swing.JButton();
        showPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        buttons.setBackground(new java.awt.Color(0, 153, 153));

        quit.setBackground(new java.awt.Color(0, 204, 255));
        quit.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        buttons.add(quit);

        toggle.setBackground(new java.awt.Color(0, 204, 255));
        toggle.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        toggle.setText("START");
        toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleActionPerformed(evt);
            }
        });
        buttons.add(toggle);

        setTime.setBackground(new java.awt.Color(0, 204, 255));
        setTime.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        setTime.setText("SET");
        setTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTimeActionPerformed(evt);
            }
        });
        buttons.add(setTime);

        getContentPane().add(buttons, java.awt.BorderLayout.NORTH);

        showPanel.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(showPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * SET ボタンの動作
     *
     * @param evt
     */
    private void setTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTimeActionPerformed
        //停止する
        toggle.setSelected(false);
        toggle.setText("START");
        timerLabel.stop();
        //設定用Dialogの表示
        int answer = JOptionPane.showOptionDialog(new JFrame(), setTimePanel,
                "時間設定", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (answer == JOptionPane.OK_OPTION) {
            //OKが押されたときに、制限時間を設定
            int m = setTimePanel.getMinute();
            int s = setTimePanel.getSecond();
            timerLabel.setMax(60 * m + s);
        } else {
            setTimePanel.setDefault();
        }
    }//GEN-LAST:event_setTimeActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
    }//GEN-LAST:event_quitActionPerformed
    /**
     * START/STOP トグルボタンの動作
     *
     * @param evt
     */
    private void toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleActionPerformed
        boolean isRunning = toggle.isSelected();
        if (isRunning) {
            toggle.setText("STOP");
            timerLabel.start();
            running = true;
            runner = new Thread(this);
            runner.start();
        } else {
            toggle.setText("START");
            timerLabel.stop();
            running = false;
        }
        showPanel.setBackground(backgroundNormal);
        pack();
    }//GEN-LAST:event_toggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JButton quit;
    private javax.swing.JButton setTime;
    private javax.swing.JPanel showPanel;
    private javax.swing.JToggleButton toggle;
    // End of variables declaration//GEN-END:variables
}
