package simpleTimer;

/**
 * 制限時間を設定するパネル
 * @author tadaki
 */
public class SetTimePanel extends javax.swing.JPanel {

    private final int minDefault = 1;
    private final int secDefault = 0;

    /**
     * Creates new form SetTimePanel
     */
    public SetTimePanel() {
        initComponents();
        minute.setText(String.valueOf(minDefault));
        second.setText(String.valueOf(secDefault));
    }

    public int getMinute() {
        int m = 0;
        try {
            m = Integer.valueOf(minute.getText());
        } catch (NumberFormatException numberFormatException) {
        }
        if (m < 0) {
            m = minDefault;
        }
        return m;
    }

    public int getSecond() {
        int s = 0;
        try {
            s = Integer.valueOf(second.getText());
        } catch (NumberFormatException numberFormatException) {
        }
        if (s > 59 || s < 0) {
            s = secDefault;
        }
        return s;
    }

    public void setDefault() {
        minute.setText(String.valueOf(minDefault));
        second.setText(String.valueOf(secDefault));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        minute = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        second = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("時間を設定");
        add(jLabel3);

        minute.setColumns(3);
        minute.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        minute.setText("jTextField1");
        add(minute);

        jLabel1.setText("分");
        add(jLabel1);

        second.setColumns(2);
        second.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        second.setText("jTextField1");
        add(second);

        jLabel2.setText("秒");
        add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField minute;
    private javax.swing.JTextField second;
    // End of variables declaration//GEN-END:variables
}
