/*
 * ShapeSamplesMain.java
 *
 * Created on 2008/11/21, 18:27
 * @author  tadaki
 */
package shapeSamples;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class ShapeSamplesMain extends javax.swing.JFrame {

    /** Creates new form ShapeSamplesMain */
    public ShapeSamplesMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new shapeSamples.DrawPanel();
        buttons = new javax.swing.JPanel();
        drawShapes = new javax.swing.JButton();
        clearImage = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);

        buttons.setBackground(new java.awt.Color(204, 255, 204));

        drawShapes.setText("Draw Shapes");
        drawShapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawShapesActionPerformed(evt);
            }
        });
        buttons.add(drawShapes);

        clearImage.setText("CLEAR");
        clearImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearImageActionPerformed(evt);
            }
        });
        buttons.add(clearImage);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        buttons.add(save);

        getContentPane().add(buttons, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void drawShapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawShapesActionPerformed
    drawPanel.drawSamples();
    drawPanel.repaint();
}//GEN-LAST:event_drawShapesActionPerformed

private void clearImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearImageActionPerformed
    drawPanel.clear();
    drawPanel.repaint();
}//GEN-LAST:event_clearImageActionPerformed

private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    JFileChooser chooser = new JFileChooser();
    FileNameExtensionFilter filter =
            new FileNameExtensionFilter("Image", "png", "jpg");
    chooser.setFileFilter(filter);
    int returnVal = chooser.showSaveDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        drawPanel.saveImage(file);
    }
}//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ShapeSamplesMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JButton clearImage;
    private shapeSamples.DrawPanel drawPanel;
    private javax.swing.JButton drawShapes;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
