/*
 * SimpleTimer.java
 *
 * Created on 2008/12/03, 20:46
 */

package simpleTimer;

/**
 *
 * @author  tadaki
 */
public class SimpleTimer extends javax.swing.JFrame {
    private Timer timerLabel;
    /** Creates new form SimpleTimer */
    public SimpleTimer() {
        initComponents();
        timerLabel=new Timer();
        buttons.add(timerLabel);
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        quit = new javax.swing.JButton();
        toggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        buttons.add(quit);

        toggle.setText("START");
        toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleActionPerformed(evt);
            }
        });
        buttons.add(toggle);

        getContentPane().add(buttons, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleActionPerformed
    boolean isRunning=toggle.isSelected();
    if(isRunning){
        toggle.setText("STOP");
        timerLabel.start();
    }else{
        toggle.setText("START");
        timerLabel.stop();
    }
    pack();
}//GEN-LAST:event_toggleActionPerformed

private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
    System.exit(0);
}//GEN-LAST:event_quitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JButton quit;
    private javax.swing.JToggleButton toggle;
    // End of variables declaration//GEN-END:variables

}
